---
# tasks file for webserver_creation

- name: Install httpd
  yum:
    name: httpd
    state: present
- name: Start httpd
  service:
    name: httpd
    state: started
    become: yes
- name: copy index.html
  copy:
    src: index.html
    dest: /var/www/html/
- name: Install php
  yum:
    name: php
    state: present
- name: Copy php file
  copy:
    src: phpinfo.php
    dest: /var/www/html/
  notify: restart httpd
