---
- name: Creates a security group
  ec2_group:
    name: "{{ name }}"
    description: This is a security group created by ansible
    region: "{{ regionname }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
- name: Creates an instance
  ec2:
    region: "{{ regionname }}"
    key_name: Ohio-region-key
    instance_type: t2.micro
    image: ami-0f7919c33c90f5b58
    wait: yes
    group: "{{ name }}"
    count: 1
    vpc_subnet_id: subnet-d5f57699
    assign_public_ip: yes
  register: ec2
